mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from seniordesign import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('seniordesign.urls')),
    path(r'', include('chatapp.urls')),
    url('index/$', views.index),

]

seniordesign/urls.py
from django.conf.urls import url
#from django.urls import path 

from . import views
from django.contrib.auth.views import LoginView


from seniordesign.views import * #(index, logout_view, userCreate)


app_name = 'seniordesign'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/*$', views.index, name='index'),
    url(r'^login/$', LoginView.as_view(template_name = "home_logged_out copy.html",
                                       redirect_field_name = "/logged_in"), name='login'),
    url(r'^homePage/*$', views.dashboard, name='homePage'),
    url(r'^myEvents/*$', views.myEvents, name='myEvents'),
    url(r'^explore/*$', views.explore, name='explore'),
               
    #url(r'^viewProfile/*$', views.dashboard, name='viewProfile'),
    #url(r'^search/*$', views.dashboard, name='search'),
    url(r'^register/$', userCreate ,name ="register"),

    url(r'^createEvent/$', views.createEventView.as_view() ,name ="createEvent"),
    url(r'^viewEvent/$', views.viewEvent ,name ="viewEvent"),
    url(r'^viewEvent2/$', views.viewEvent2 ,name ="viewEvent2"),
    url(r'^viewEvent3/$', views.viewEvent3 ,name ="viewEvent3"),
    url(r'^viewEvent4/$', views.viewEvent4 ,name ="viewEvent4"),
               
    
    url(r'^updateProfile/$', views.editUser, name='updateProfile'),           

    url(r'^viewProfile/$', views.viewProfile, name='viewProfile'),  
    url(r'^search/$', views.search, name='search'),      
    #url(r'^viewProfile/$', views.AccountDetailView.as_view() ,name='viewProfile'),
               
    #The next two need their template names, add the names after the html files are added to proj
    
    url(r'^loginErrors/$', LoginView.as_view(template_name = ".html",redirect_field_name = "/logged_in"), name='loginErrors'),
    
    url(r'^log_out/$', logout_view ,name ="log_out"),
    

]
 

seniordesign/forms.py
from django import forms
from django.forms import ModelForm
from seniordesign.models import *


from django.contrib.auth.forms import ReadOnlyPasswordHashField


from django.contrib.auth import get_user_model
User = get_user_model()

class createEventForm(forms.ModelForm):
    class Meta:
        model = EventProfile
        fields = ('date', 'time', 'Location', 'tags', 'Eventname', 'Host','Location',)


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']


class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('email',)

    #This function not here originally, added!
    def clean_email(self):
        #Check that the e-mail is not already taken
        email = self.cleaned_data.get('email')
        qs = CustomUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

seniordesign/views.py
from django.shortcuts               import render, HttpResponseRedirect
from django.http                    import HttpResponse
from django.core.mail               import EmailMessage
from django.shortcuts               import redirect, render
from django.template                import loader
from django                         import forms
from seniordesign.models            import CustomUser, UserProfile, UserManager, uConnectUser, EventProfile
from seniordesign.forms             import createEventForm, UserForm

from django.views                   import View
from django.views.generic           import TemplateView, ListView, DetailView, CreateView
from django.contrib.auth.views      import LoginView
from django.contrib.auth            import authenticate, login, logout, get_user
from django.contrib.auth.mixins     import LoginRequiredMixin
from django.db.models               import Q
from django.contrib                 import messages
from django.http                    import HttpResponse, HttpResponseRedirect,HttpRequest
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models     import User
from django.forms.models            import inlineformset_factory
from django.core.exceptions         import PermissionDenied
import os

site_hdr = "uConnect"



class createEventView(TemplateView):
    def __init__(self):
        self.template_name= 'createEvent.html'
    
    def get(self, request):
        form = createEventForm()
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = createEventForm(request.POST)
        if form.is_valid():
            form.save()
            #text = form.cleaned_data['POST']
            form = createEventForm()
            return redirect('seniordesign:viewEvent')

        args = {'form':form, 'text': text}
        return render(request, self.template_name, args)



def index(request):
    return render(request, 'index.html', {'header': site_hdr})

def dashboard(request):
    return render(request, 'dashboard.html', {'header': site_hdr})

def myEvents(request):
    queryset = uConnectUser.objects.filter(user = request.user)
    for user in queryset:
        print(user.myEvents.all())
    return render(request, 'myEvents.html', {'header': site_hdr})

def explore(request):
    queryset = EventProfile.objects.all().values()
    topEvents = []
    for e in queryset:
        if e['id'] > 7:
            print(e)
            topEvents.append(e['Eventname'])
    #topEvents.append(e.values())
    return render(request, 'explore.html', {'header': site_hdr, 'topEvents': topEvents})

def viewEvent(request):
    return render(request, 'viewEvent.html', {'header': site_hdr})

def viewEvent2(request):
    return render(request, 'viewEvent2.html', {'header': site_hdr})

def viewEvent3(request):
    return render(request, 'viewEvent3.html', {'header': site_hdr})

def viewEvent4(request):
    return render(request, 'viewEvent4.html', {'header': site_hdr})

def logout_view(request):
    logout(request)
    return redirect('login')


def isEmailPresent(email):
    return User.objects.filter(email=email).exists()
    
def isUsernamePresent(username):
    return UserProfile.objects.filter(username=username).exists()
    #weird error here, userprofile should be one to one with user

def isPasswordValid(password):
    if len(password) in range(8,15):
        return True
    else:
        return False




#@login_required        
'''
class AccountDetailView(LoginRequiredMixin, ListView):
    def __init__(self):
        self.template_name= 'account/viewProfile.html'

    def get_queryset(self):
        queryset = uConnectUser.objects.filter(user = self.request.user)
        print(queryset)
        return render(self.request, 'account/viewProfile.html', {'header': site_hdr, 'queryset': queryset})
        #return render(request, 'account/viewProfile.html', {'header': site_hdr, 'queryset': queryset})
'''
@login_required  
def viewProfile(request):
    queryset = uConnectUser.objects.filter(user = request.user)
    return render(request, 'account/viewProfile.html', {'header': site_hdr, 
                                                        'FirstName': queryset[0].user.first_name,
                                                        'LastName': queryset[0].user.last_name,
                                                        'username': queryset[0].username, 
                                                        'uni':queryset[0].university, 
                                                        'year_in_school':queryset[0].year_in_school })


@login_required
def editUser(request):
    user_form = UserForm(instance=request.user)
 
    ProfileInlineFormset = inlineformset_factory(User, uConnectUser, fields=('username', 'university', 'year_in_school'))
    formset = ProfileInlineFormset(instance=request.user)
 
    if request.user.is_authenticated:
        if request.method == "POST":
            user_form = UserForm(request.POST, request.FILES, instance=request.user)
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=request.user)
 
            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)
 
                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect('/viewProfile/')

 
        return render(request, "account/updateProfile.html", {
            "noodle": request.user,
            "noodle_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied
 

@login_required
def search(request):
    searchQuery = request.GET['search']
    allEvents = EventProfile.objects.all()
    returnEvents = []

    #check matching tags
    for event in allEvents:
        allTags = event.tags
        if searchQuery in allTags:
            returnEvents.append(event)

    #format output
    returnedOutput = {}
    returnedOutput['header'] = site_hdr
    resultEvents = []
    for event in returnEvents:
        resultEvents.append(event)
    returnedOutput['allEvents'] = resultEvents

    #render the resulting page
    return render(request, "search.html", returnedOutput)

def userCreate(request):
    if request.method == 'POST':
        fName           = str(request.POST.get('fName', ''))
        lName           = str(request.POST.get('lName', ''))
        university      = str(request.POST.get('university', ''))
        email           = str(request.POST.get('email', ''))
        username        = str(request.POST.get('username', ''))
        password        = str(request.POST.get('password', ''))
        confirmPassword = str(request.POST.get('confirmPassword', ''))
        '''
        print(fName)
        print(lName)
        print(email)
        print(username)
        '''
        # now for some form validation
        #first check database for existing userid and email since these need to be unique to each user

                    
        if isEmailPresent(email):
            messages.error(request,"This email is already registered to an existing user!")
            

        if isUsernamePresent(username):
            messages.error(request,"This username already belongs to an existing user!")
            


        if not isEmailPresent(email) and not isUsernamePresent(username):
            # this is checking to make sure first name and last name only include letters
            isFNameValid        = fName.isalpha()  
            isLNameValid        = lName.isalpha()
            isUserNameValid     = True if username.isalnum() and len(username) in range(5,12)   else False
            isNyuEmail          = True if "@nyu.edu" in email                                   else False   #Currently only serves NYU
            passwordsMatch      = True if password == confirmPassword                           else False

            if not isFNameValid: messages.error(request,"The First Name Entered is not Valid!")
            
            if not isLNameValid: messages.error(request,"The Last Name Entered is not Valid!")

            if not isUserNameValid: messages.error(request,"Username should only include letters and numbers and be between 5 and 12 characters long!")
            
            if not isNyuEmail: messages.error(request, "Please use the email associated with your university!")
            
            if not passwordsMatch: messages.error(request, "Please make sure that the passwords match!")
            
            elif passwordsMatch: #already confirmed that they match, now checking if it's valid
                isValid = isPasswordValid(password)
                if not isValid:
                    messages.error(request, "Passwords should be between 8 and 15 characters!")

            if isFNameValid and isLNameValid and isUserNameValid and isNyuEmail and passwordsMatch and isPasswordValid(password):
                #create instance of user and save to db
                print("here")
                newUser = User(email=email)
                newUser.set_password(password)
                newUser.save()

                newUserProfile = UserProfile()
                newUserProfile.user = newUser
                newUserProfile.firstName = fName
                newUserProfile.lastName = lName
                newUserProfile.username = username
                newUserProfile.university = university
                newUserProfile.save()
                

                user = authenticate(username = email, password = password)
                login(request, user)
                return HttpResponseRedirect('')
                #Need Redirect to be filled ^^

seniordesign/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {{ header }}
        {% endblock title %}
    </title>
    {% block stylesheets %}
        {% load static %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
        
       
        <link rel="stylesheet" type="text/css" href="/static/seniordesign/style.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock stylesheets %}
</head>
<body class="dashboard">
    <div id="container">
        <div id="header">
	    <div id="user-tools">
                <a href="/seniordesign/index">Home</a>
                &nbsp; &nbsp; 
                <a href="/seniordesign/imageresizer">Image Resizer</a>
                &nbsp; &nbsp; 
                <a href="/seniordesign/spellchecker">Spell Checker</a>
            </div>
            <div>
                <h1>{{ header }}</h1>
            </div>
        </div>
        <br> 
        <div id="content" class="colMS">
            <div id="content-main">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
</body>
</html>

seniordesign/templates/base2.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
        {{ header }}
        {% endblock title %}
    </title>
    {% block stylesheets %}
        {% load static %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="/static/seniordesign/style.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock stylesheets %}
</head>
<body class="dashboard">
    <div id="container">
        <div id="header" style="height:auto; width:auto">
    	    <div id="user-tools">
                <a href="/homePage">Home</a>
                &nbsp; &nbsp; 
                <a href="/viewProfile">View Profile</a>
                &nbsp; &nbsp;

                <form action="/search">
                  <input type="text" placeholder="Search Events..." name="search">
                  <button type="submit"><i class="fa fa-search"></i></button>
                </form>

            </div>
            <div style="height:100%; text-align: left">
                <a href = "/homePage"><h1>uConnect</h1></a>
            </div> 
        </div>
        <br> 
        <div id="content" class="colMS">
            <div id="content-main">
                    <link rel="stylesheet" href="{% static "seniordesign/sidebar_style.css" %}">

                    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
                
                    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
                    
                
                <div class="wrapper">
                
                    <nav id="sidebar">
                        <div class="sidebar-header">
                            <h3 style="text-align:center">Dashboard</h3>
                        </div>
                
                        <ul class="list-unstyled components">
                            <li class="active">
                                
                                    <a href = '/myEvents'><h4 style="margin:0px;padding: 0px">My Events</h4></i></a> 
                                
                            </li>
                            <li>
                                
                                    <a href = '/explore'><h4 style="margin:0px;padding: 0px">Explore</h4></i></a> 
                                    <a href ="/createEvent"><h4 style="margin:0px;padding: 0px">Create Event</h4></i></a>
                              
                                
                            </li>
                        </ul>
                
                    </nav>
                
                   
                    <div id="content">
                
                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                            <div class="container-fluid">
                
                                <button type="button" id="sidebarCollapse" class="btn btn-info">
                                   </i>
                                    <span>Toggle Sidebar</span>
                                </button>
                                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <i class="fas fa-align-justify"></i>
                                </button>
                
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                                </div>
                
                            </div>
                        </nav>
                
                        {% block content %}
                        {% endblock content %}
                    </div>
                </div>
                
                <script>
                $(document).ready(function () {
                
                    $('#sidebarCollapse').on('click', function () {
                        $('#sidebar').toggleClass('active');
                    });
                
                });
                
                </script>
                

              
            </div>
        </div>
    </div>
</body>
</html>

seniordesign/templates/createEvent.html
{% extends "base2.html" %}

{% block content%}
{% load static %}

<h4>Tell us a little bit about your event!</h4>

<form method="POST">
    {% csrf_token %}
    {{ form.as_ul }}
    <button type="submit">Submit</button>
</form>

{% endblock content%}

seniordesign/templates/home_logged_out copy.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load widget_tweaks %}
<meta charset = "utf-8">
            <meta name = "viewport" content="width=device-width, initial-scale=1">
                


                    <script src="https://code.jquery.com/jquery-3.1.1.min.js">
                        </script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js">
                        </script>
                    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js">
                        </script>
                    
                    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
                        
                        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

                    
                    
                    
                    <style>
                        a.main_page{
                            font-size: 25px;
                            font-family:'GrandHotelRegular';
                            
                        }
                        
                        
                        a.main_page:link, a.main_page:hover, a.main_page:active{
                            color: white;
                            text-decoration:none;
                            
                            
                        }
          
                
                    .welcome_splash{
                        font-family: 'CaviarDreams';
                        text-align: center;
                        color: white;
                    }
                    body{
                        
                        
                        background-color:gray;
                    }
                    
                    .main_pageLoginInput{
                        width:100%;max-width:300px;border-radius:15px;background-color:#439DBB9F;color:white;
                    }

                    input.main_pageLoginInput:focus {
                        outline-width: 0;
                    }

                    {% load static %}

                    @font-face{
                       font-family: 'CaviarDreams';
                       src: url("{% static 'caviar_dreams/CaviarDreams.ttf' %}");
                     }
                        </style>
    <h1>Senior Design</h1>
    <div class = "jumbotron" style="background-color: #439DBB0A;margin-bottom:0px;text-align: center;">
        <h1 class = "welcome_splash">welcome to university Connect!</h1>
    </div>

    <div style = "background-color:#439DBB0A;width:50%;margin:auto;border-radius:5px;">
        <form method = "POST" action="{% url 'seniordesign:login' %}" > {% csrf_token %}
    <div class = "container" style="margin-bottom:10px;clear:left;text-align:center;">
        <div class = "form-label" style="color:white;font-family: 'CaviarDreams';">
                {{ form.username.label_tag }}
        </div>
        <div  style = "width:100%;max-width:300px;border-radius:15px;background-color:#439DBB9F;color:white;text-align:center;margin-left:25%;">{{ form.username }}</div>
       
            
    </div>
    
    <div class = "container" style="margin-bottom:10px;clear:left;text-align:center;">
        <div class = "form-label" style="color:white;font-family: 'CaviarDreams';">
                {{ form.password.label_tag }}
        </div>
        
       <div style = "width:100%;max-width:300px;border-radius:15px;background-color:#439DBB9F;color:white;margin-left:25%;">{{ form.password }}</div>
       
            
    </div>
        

        <div style="text-align:center;">
            <div style = "margin-bottom:10px;">
            <button type= "submit" class="btn btn-link" style="color:white;  border:1px solid; border-radius: 15px;font-family: 'CaviarDreams';">Login</button>
            <input type="hidden" name="next" value="/homePage/" />
            </div>
            <a id = "forgotPassword" class= "main_page" style="color:white;font-family: 'CaviarDreams';">Forgot your password?</a><br>
            <a id = "createAccount" class= "main_page" data-toggle = "modal" data-target="#myModal" style="color:white;font-family: 'CaviarDreams';">Don't have an account? Create one right now!</a>
        </div>
    </form>
    </div>
    

    
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form method = "POST" name="registration" onsubmit="return formValidation();"> {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel" >Creating an Account is Easy!</h5>
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p style = "text-align:center;">Step 1: Let us know a bit about yourself!</p>
                    <div class="form-group">
                        <div class = "row">
                            <div style ="float:left;padding:10px;width:50%;">
                                <label label-default="" for="Fname" class="col-sm-6"> First Name:</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="Fname" name="firstName" placeholder="First Name" required  >
                            </div>
                            
                            </div>
                        <div style = "float:right;padding:10px;width:50%;">
                            <label label-default="" for="Lname" class="col-sm-6" > Last Name:</label>
                            <div class="col-sm-12">
                                <input type="text" class="form-control" id="Lname" name="lastName" placeholder="Last Name" required>
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label label-default="" for="school" class="col-sm-12"> School/University:</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="school" name="university" placeholder="School/University" required>
                                </div>
                    </div>
                    
                    <div class="form-group">
                        <label label-default="" for="email" class="col-sm-12"> Email Address:</label>
                        <div class="col-sm-12">
                            <input type="email" class="form-control" id="email" name="email" placeholder="example@university.edu" required>
                            </div>
                    </div>
                    
                    <div class="form-group">
                        <label label-default="" for="username" class="col-sm-12"> Username:</label>
                        <div class="col-sm-12">
                            <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                                </div>
                    </div>
                    <div class="form-group">
                        <label label-default="" for="password" class="col-sm-12">Enter a Password:</label>
                        <div class="col-sm-12">
                            <input type="password" class="form-control" id="password" name="password" placeholder="" required>
                                </div>
                    </div>
                    <div class="form-group">
                        <label label-default="" for="confirmPass" class="col-sm-12">Confirm Password:</label>
                        <div class="col-sm-12">
                            <input type="password" class="form-control" id="confirmPass" name="confirmPass" placeholder="" required>
                                </div>
                    </div>



                </div>
            
                <div class="modal-footer">
                    <button id="registerBtn" type="submit" class="btn btn-primary" >Next Step!</button>
                </div>
            </form>
            </div>
        </div>
    </div>

  





{% endblock  %}

seniordesign/templates/myEvents.html
{% extends "base2.html" %}

{% block content %}

{% load static %}
<div class = "jumbotron" style="padding:0%;">
  <h2>My Events</h2>
</div>
<div class="row">
  <div class ="col" style="text-align:center">
      <a href = "/viewEvent">
    <div class="container fluid">
        <img src="{% static "seniordesign/poker?,_i_barely_know_er.jpg" %}" height="176px" width="auto">
    </div>
     <h7 style="text-align:center;color:blue;">POKER NIGHT</h7> </a>
  </div>



  <div class ="col" style="text-align:center">
      <a href = "/viewEvent2">
   <div class="container fluid">
      <img src="{% static "seniordesign/pooliosis.jpg" %}" height="176px" width="176px">
    </div>
     <h7 style="text-align:center;color:blue;">Pool & Billiards</h7> </a>
  </div>

  <div class ="col" style="text-align:center">
      <a href = "/viewEvent3">
    <div class="container fluid"> 
      <img src="{% static "seniordesign/debate.gif" %}" height="176px" width="176px">
    </div>
    <h7 style="text-align:center;color:blue;">Master Debating Tournament</h7> </a>
  </div>

  <div class ="col" style="text-align:center">
      <a href = "/viewEvent4">
    <div class="container fluid"> 
      <img src="{% static "seniordesign/food.jpg" %}" height="176px" width="176px">
    </div>
    <h7 style="text-align:center;color:blue;">Free Food, Just take it</h7> </a>
  </div>

</div>


      
{% endblock content %}